plugin:
  has_options: true
  icon: Icappad.png
  resources:
      # "class" is the entity of your resource. This may be the entity of a existing
      # resource of the platform. This entity defines how the resource is stocked.
      # It may be usefull is your resource is a zip file with a particular structure.
      # In this case you can extend *Claroline\CoreBundle\Entity\Resource\File*.
    - class: Icap\PadBundle\Entity\PadAggregate
      # Your resource type name
      name: Icap_pad_aggregate
      # Do you want your resource to be exported as a part of a workspace model ?
      # Note: the default value of this parameter is "false"
      is_exportable: false
      # Icon for your resource.
      # They must be stored in the Resource/public/images/icon
      icon: Icappad.png
      # Which are the actions we can fire from the resource manager.
      # Note that the resource manager will set some defaults actions
      #  (parameters, delete and download).
      # The name field allow you to chose an existing action ('open', 'delete', 'edit') or
      # to create a new one if the Claroline core couldn't find your action name.
      # The menu_name is optional. This will append a menu for your resource name with the menu_name you picked.
      # You can translate them in with a translation file from the resource domain.
      # You will be able to use these actions as a parameter for the isGranted() method.